### PR TITLE
Problem with Symphony framework version

### PR DESCRIPTION
**Pull request by chrodos**
Check issue #2277 in DKAN https://github.com/GetDKAN/dkan/issues/2277

### CODE REVIEW

**Comment by janette** [comment]
@chrodos could you create your PR against the library repo? https://github.com/symfony/serializer

**Comment by janette** [comment]
Sorry @chrodos I sent you to the wrong repo, the fix should be applied to https://github.com/symfony/symfony

**Comment by chrodos** [comment]
I think I figured out what is the problem. Here it goes dkan-7.x-1.14 uses symphony 4.0.0 (https://github.com/GetDKAN/dkan-drops-7/blob/master/profiles/dkan/libraries/symfonyserializer/CHANGELOG.md).

Symphony version 4.0.0 requires PHP 7.1.3 (https://symfony.com/doc/current/reference/requirements.html).

Drupal version 7.56 requires PHP >5.2 (https://www.drupal.org/docs/7/system-requirements/php)

I have dkan-7.x-1.14 installed on PHP 7.0 so the ?string notation in Symphony version 4.0.0 is valid in PHP 7.1 but not in previous PHP versions.

According to dkan-7.x-1.14 documentation, its installation requires PHP >=5.3

> PHP: minimum version 5.3.x

So, the option is to downgrade the symphony framework if there is no need for symphony 4.0.0 or change dkan-7.x-1.14 requirements. I

**Comment by janette** [comment]
This will be fixed in the next release https://github.com/GetDKAN/open_data_schema_map/pull/110

**Pull request closed without merging**
